name: Code Coverage Report (remote trigger using API)
description: Comments a pull request with the code coverage
author: Ayush Gaud
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  lcov-dump:
    description: lcov.info dump
    required: false
  pull-request-id:
    description: Comment results on given PR
    required: false
runs:
  using: node12
  main: dist/main.js
